#!/bin/bash

# Create bootstrap.css

lessc less/bootstrap.less > css/bootstrap.css

# Upload bootstrap.css

cd css/
HOST='kokakolako.de'
USER='ftp10961081-admin'
PASSWD='(PapaPup$764)'

ftp -n -v $HOST << EOT
ascii
user $USER $PASSWD
prompt
cd /jko/css
put "bootstrap.css"
bye
EOT

# Fetch and Upload bootstrap.js

cd ~/Projekte/bin/jko/js
HOST='kokakolako.de'
USER='ftp10961081-admin'
PASSWD='(PapaPup$764)'

ftp -n -v $HOST << EOT
ascii
user $USER $PASSWD
prompt
cd /jko/js
put "bootstrap.js"
bye
EOT