#!/bin/sh

# get the name of the project directory
if [ -z $1 ];
	then
		echo "Wie willst du dein neues Projekt benennen? "
		read project_name
	else
		project_name=$1
fi

if [ $1=="server" ];
	then
		python -m SimpleHTTPServer 8000
fi

# create the project directory
sudo mkdir $project_name
cd $project_name

# create the default files (style.css + functions.js) and directorys
sudo mkdir css lib js img
sudo touch css/style.css js/functions.js
echo "Der Projekt Ordner \"$project_name\" wurde erfolgreich erstellt"

# installation of bootstrap, modernizr, jquery
bower install bootstrap modernizr jquery

# compilation of the bootstrap stylesheets
lessc lib/bootstrap/less/bootstrap.less > css/bootstrap.css
echo "Bootstrap, Modernizr und jQuery wurden erfolgreich deinem Projekt hinzugefügt"

# customize the index.html
cat /opt/kokaplate/lib/index.html | pyp "p.replace('[[project_name]]', '$project_name')" > index.html

# initialize git
git init
git add .
git commit -m "initial commit"